version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-3.2.0
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - 3307:3306

  php:
    image: wodby/drupal-php:7.2-4.5.1
    environment:
      PHP_SITE_NAME: dev
      # This is the URL to access the Drupal site.
      PHP_HOST_NAME: localhost:8000
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
    volumes:
      # Note: ":cache" option is working on MacOS and OSX systems only!
      - ./web:/var/www/html:cached
      - ./config:/var/www/config:cached

  nginx:
    image: wodby/drupal-nginx:8-1.14-4.1.0
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_BACKEND_HOST: php
      NGINX_UPSTREAM_NAME: php
      # For using images from PROD.
      # NGINX_DRUPAL_FILE_PROXY_URL: https://example.com
      DRUPAL_VERSION: 8
    depends_on:
      - php
    volumes_from:
      - php
    ports:
      - "8000:80"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8008:8025"

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
      ADMINER_DESIGN: galkaev
    ports:
      - 8080:8080
